### ISSUE TITLE
Flaky test KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed on machines with more than 4 CPUs on 2.11.1

### ISSUE THREAD

**Issue by salyh** [opensearch-project/k-NN#1392] opened 2024-01-18 10:10 UTC
**What is the bug?**

Unit test KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed fails on machines with more than 4 CPUs.
On machines with fewer cores its green and looks stable

```
 org.opensearch.knn.index.KNNSettingsTests > testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed FAILED
    java.lang.AssertionError: no warnings, expected: [[index.store.hybrid.mmap.extensions] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version., no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release]
        at __randomizedtesting.SeedInfo.seed([F01086BC8EEF63CB:61987A4E1BA5D039]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:578)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:564)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:518)
        at org.opensearch.knn.index.KNNSettingsTests.assertWarnings(KNNSettingsTests.java:172)
        at
org.opensearch.knn.index.KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed(KNNSettingsTests.java:90)
``` 

```
  1> [2024-01-18T09:56:09,889][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed] closing ...
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertNotNull(Assert.java:713)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:578)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:564)
        at org.opensearch.test.OpenSearchTestCase.assertWarnings(OpenSearchTestCase.java:518)
        at org.opensearch.knn.index.KNNSettingsTests.assertWarnings(KNNSettingsTests.java:172)
        at org.opensearch.knn.index.KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed(KNNSettingsTests.java:90)
```
```

 Tests with failures:
 - org.opensearch.knn.index.KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed
461 tests completed, 1 failed, 2 skipped
```

**How can one reproduce the bug?**
1. Run the unit tests on a machine with 8 cpu cores

`REPRODUCE WITH: ./gradlew ':test' --tests "org.opensearch.knn.index.KNNSettingsTests.testFilteredSearchAdvanceSetting_whenNoValuesProvidedByUsers_thenDefaultSettingsUsed" -Dtests.seed=F01086BC8EEF63CB -Dtests.security.manager=false -Dtests.locale=ar-KW -Dtests.timezone=Australia/Darwin -Druntime.java=17`

**What is the expected behavior?**
Test succeeds

**What is your host/environment?**
 - OS: Ubuntu x86
 - Version 22.04
 - OpenSearch/k-NN 2.11.1

**Do you have any additional context?**
There are a few other tests flakythe same way. I open extra issues for them.

**Comment by junqiu-lei** [comment] 2024-01-26 18:14
Hi @salyh, I tried to reproduce the issue on 8 CPUs desktop on Amazon Linux 2 OS, however all tests passed in KNNSettingsTests, no failure found.

```
./gradlew ':test' --tests "org.opensearch.knn.index.KNNSettingsTests.*" -Dtests.seed=F01086BC8EEF63CB -Dtests.security.manager=false -Dtests.locale=ar-KW -Dtests.timezone=Australia/Darwin -Druntime.java=17

...

-- OS:                Linux
-- Compiler:          GNU 7
-- CXX flags release: -Wall -Wunreachable-code -Wcast-align -Ofast -lm -DNDEBUG -std=c++11 -pthread  -DHAVE_CXX0X  -march=native -Wl,--no-as-needed -fpic
-- CXX flags debug:   -Wall -Wunreachable-code -Wcast-align -ggdb  -lm -DNDEBUG -std=c++11 -pthread  -DHAVE_CXX0X  -march=native -Wl,--no-as-needed -fpic
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Could NOT find MKL (missing: MKL_LIBRARIES) 
-- Configuring done (0.0s)
-- Generating done (0.0s)
-- Build files have been written to: /local/home/junqiu/k-NN/jni/googletest-download
[ 11%] Performing update step for 'googletest'
[ 22%] No patch step for 'googletest'
[ 33%] No configure step for 'googletest'
[ 44%] No build step for 'googletest'
[ 55%] No install step for 'googletest'
[ 66%] No test step for 'googletest'
[ 77%] Completed 'googletest'
[100%] Built target googletest
-- Configuring done (1.0s)
-- Generating done (0.1s)
-- Build files have been written to: /local/home/junqiu/k-NN/jni

> Task :buildJniLib
[ 89%] Built target NonMetricSpaceLib
[ 94%] Built target opensearchknn_common
[100%] Built target opensearchknn_nmslib
[ 93%] Built target faiss
[ 96%] Built target opensearchknn_common
[100%] Built target opensearchknn_faiss

> Task :test
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 24s
15 actionable tasks: 6 executed, 9 up-to-date
```

**Comment by junqiu-lei** [comment] 2024-01-30 17:27
@salyh Yes, I tried rerun for 10 times by both single unit test in `KNNSettingsTests` and `KNNSettingsTests.*`, all tests passed.

**Comment by jmazanec15** [comment] 2024-01-31 17:57
@salyh Can you try switching assertWarnings -> allowWarnings in the KNNSettingsTest file and see if it is resolved? I cant reproduce locally either.

For ref, here is example of assertWarnings: https://github.com/opensearch-project/k-NN/blob/main/src/test/java/org/opensearch/knn/index/KNNSettingsTests.java#L75

**Comment by jmazanec15** [comment] 2024-02-01 20:20
Also @salyh can you paste output on failure from `build/test-results/test/binary/output.bin` file?

**Comment by junqiu-lei** [comment] 2024-02-05 22:55
Thanks for providing more details on the reproduce steps. @salyh 

However I still couldn’t reproduce the issue with multiple times run using the same env mentioned above:
```
OS: Ubuntu 22.04
EC2: t2.2xlarge
Docker Image: opensearchstaging/ci-runner:ci-runner-centos7-opensearch-build-v3
```
[knn-settings-tests-output.log](https://github.com/opensearch-project/k-NN/files/14172660/knn-settings-tests-output.log)


cc: @jmazanec15

**Comment by jmazanec15** [comment] 2024-02-07 19:22
@salyh I was able to reproduce the issue. Below you can see the warning is in the one long but not other. Im not sure why this is happening. Given we arent really testing this, I think we should remove the assertWarnings altogether and then set 
[`enableWarningCheck`](https://github.com/opensearch-project/OpenSearch/blob/main/test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java#L422-L424) in `KNNTestCase` to false and remove the assertWarning checks. @junqiu-lei can you update your PR to do this?

For the failure, I see
```
Suite: Test class org.opensearch.knn.index.KNNSettingsTests
  1> [2024-02-07T14:31:35,368][INFO ][o.o.k.i.KNNSettingsTests ] [testGetSettingValueDefault] before test
  1> [2024-02-07T14:31:35,428][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] version[2.11.1-SNAPSHOT], pid[2275], build[unknown/6b1986e964d440be9137eba1413015c31c5a7752/2023-11-29T21:17:26.630182988Z], OS[Linux/6.2.0-1017-aws/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.3/17.0.3+7]
  1> [2024-02-07T14:31:35,434][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] JVM home [/opt/java/openjdk-17]
  1> [2024-02-07T14:31:35,435][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] JVM arguments [-Dgradle.dist.lib=/home/ci-runner/.gradle/wrapper/dists/gradle-7.6.1-all/942lu1p9i6mhoyzmt401s4g74/gradle-7.6.1/lib, -Dgradle.user.home=/home/ci-runner/.gradle, -Dgradle.worker.jar=/home/ci-runner/.gradle/caches/7.6.1/workerMain/gradle-worker.jar, -Dio.netty.noKeySetOptimization=true, -Dio.netty.noUnsafe=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Djava.awt.headless=true, -Djava.library.path=/home/ci-runner/k-NN/jni/release, -Djava.locale.providers=SPI,COMPAT, -Djdk.attach.allowAttachSelf=true, -Djna.nosys=true, -Dopensearch.scripting.update.ctx_in_params=false, -Dopensearch.search.rewrite_sort=true, -Dopensearch.transport.cname_in_publish_address=true, -Dorg.gradle.internal.worker.tmpdir=/home/ci-runner/k-NN/build/tmp/test/work, -Dorg.gradle.native=false, -Dtests.artifact=opensearch-knn, -Dtests.gradle=true, -Dtests.logger.level=WARN, -Dtests.security.manager=false, -Dtests.seed=1D74642C8A5A3ABE, -Dtests.task=:test, -XX:+HeapDumpOnOutOfMemoryError, -esa, --illegal-access=warn, -javaagent:../../tmp/expandedArchives/org.jacoco.agent-0.8.7.jar_3a83c50b4a016f281c4e9f3500d16b55/jacocoagent.jar=destfile=../../jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false, -XX:HeapDumpPath=/home/ci-runner/k-NN/build/heapdump, -Xms512m, -Xmx512m, -Dfile.encoding=US-ASCII, -Djava.io.tmpdir=/home/ci-runner/k-NN/build/testrun/test/temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
  1> [2024-02-07T14:31:35,436][WARN ][o.o.n.Node               ] [testGetSettingValueDefault] version [2.11.1-SNAPSHOT] is a pre-release version of OpenSearch and is not suitable for production
  1> [2024-02-07T14:31:35,437][INFO ][o.o.p.PluginsService     ] [testGetSettingValueDefault] no modules loaded
  1> [2024-02-07T14:31:35,438][INFO ][o.o.p.PluginsService     ] [testGetSettingValueDefault] loaded plugin [org.opensearch.knn.plugin.KNNPlugin]
  1> [2024-02-07T14:31:35,439][INFO ][o.o.p.PluginsService     ] [testGetSettingValueDefault] loaded plugin [org.opensearch.test.MockHttpTransport$TestPlugin]
  1> [2024-02-07T14:31:35,439][INFO ][o.o.p.PluginsService     ] [testGetSettingValueDefault] loaded plugin [org.opensearch.transport.nio.MockNioTransportPlugin]
  1> [2024-02-07T14:31:35,440][INFO ][o.o.e.ExtensionsManager  ] [testGetSettingValueDefault] ExtensionsManager initialized
  1> [2024-02-07T14:31:35,442][INFO ][o.o.e.NodeEnvironment    ] [testGetSettingValueDefault] using [1] data paths, mounts [[/ (overlay)]], net usable_space [475.7gb], net total_space [484.4gb], types [overlay]
  1> [2024-02-07T14:31:35,443][INFO ][o.o.e.NodeEnvironment    ] [testGetSettingValueDefault] heap size [512mb], compressed ordinary object pointers [true]
  1> [2024-02-07T14:31:35,445][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] node name [mock_ node], node ID [khb1hv__T_-1TgEdAAAAAA], cluster name [single-node-cluster-TEST_WORKER_VM=[4]-CLUSTER_SEED=[-7299691990438868214]-HASH=[11793E818C7]], roles [ingest, remote_cluster_client, data, cluster_manager]
  1> [2024-02-07T14:31:35,492][INFO ][o.o.d.DiscoveryModule    ] [testGetSettingValueDefault] using discovery type [zen] and seed hosts providers [settings]
  1> [2024-02-07T14:31:35,517][WARN ][o.o.g.DanglingIndicesState] [testGetSettingValueDefault] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
  1> [2024-02-07T14:31:35,533][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] initialized
  1> [2024-02-07T14:31:35,533][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] starting ...
  1> [2024-02-07T14:31:35,543][INFO ][o.o.t.TransportService   ] [testGetSettingValueDefault] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
  1> [2024-02-07T14:31:35,544][INFO ][o.o.t.TransportService   ] [testGetSettingValueDefault] Remote clusters initialized successfully.
  1> [2024-02-07T14:31:35,583][INFO ][o.o.c.c.ClusterBootstrapService] [testGetSettingValueDefault] no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing cluster-manager is discovered
  1> [2024-02-07T14:31:38,585][INFO ][o.o.c.c.Coordinator      ] [mock_ node] setting initial configuration to VotingConfiguration{khb1hv__T_-1TgEdAAAAAA}
  1> [2024-02-07T14:31:38,667][INFO ][o.o.c.s.MasterService    ] [mock_ node] elected-as-cluster-manager ([1] nodes joined)[{mock_ node}{khb1hv__T_-1TgEdAAAAAA}{M1AqfQa7Ss6ZWFmUO2xITA}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: cluster-manager node changed {previous [], current [{mock_ node}{khb1hv__T_-1TgEdAAAAAA}{M1AqfQa7Ss6ZWFmUO2xITA}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]}
  1> [2024-02-07T14:31:38,679][INFO ][o.o.c.c.CoordinationState] [mock_ node] cluster UUID set to [qsOtR5etRb2NaDYVWFR69g]
  1> [2024-02-07T14:31:38,691][INFO ][o.o.c.s.ClusterApplierService] [mock_ node] cluster-manager node changed {previous [], current [{mock_ node}{khb1hv__T_-1TgEdAAAAAA}{M1AqfQa7Ss6ZWFmUO2xITA}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
  1> [2024-02-07T14:31:38,693][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] started
  1> [2024-02-07T14:31:38,693][INFO ][o.o.d.PeerFinder         ] [mock_ node] setting findPeersInterval to [1s] as node commission status = [true] for local node [{mock_ node}{khb1hv__T_-1TgEdAAAAAA}{M1AqfQa7Ss6ZWFmUO2xITA}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]
  1> [2024-02-07T14:31:38,693][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] stopping ...
  1> [2024-02-07T14:31:38,698][INFO ][o.o.g.GatewayService     ] [mock_ node] recovered [0] indices into cluster_state
  1> [2024-02-07T14:31:38,700][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] stopped
  1> [2024-02-07T14:31:38,700][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] closing ...
  1> [2024-02-07T14:31:38,702][INFO ][o.o.n.Node               ] [testGetSettingValueDefault] closed
  1> [2024-02-07T14:31:38,703][INFO ][o.o.k.i.KNNSettingsTests ] [testGetSettingValueDefault] after test
```

for a passing one, I see
```
1> [2024-02-07T14:31:38,732][INFO ][o.o.k.i.KNNSettingsTests ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] before test
  1> [2024-02-07T14:31:38,737][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] version[2.11.1-SNAPSHOT], pid[2275], build[unknown/6b1986e964d440be9137eba1413015c31c5a7752/2023-11-29T21:17:26.630182988Z], OS[Linux/6.2.0-1017-aws/amd64], JVM[Eclipse Adoptium/OpenJDK 64-Bit Server VM/17.0.3/17.0.3+7]
  1> [2024-02-07T14:31:38,737][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] JVM home [/opt/java/openjdk-17]
  1> [2024-02-07T14:31:38,737][DEPRECATION][o.o.d.n.Node             ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] no-jdk distributions that do not bundle a JDK are deprecated and will be removed in a future release
  1> [2024-02-07T14:31:38,738][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] JVM arguments [-Dgradle.dist.lib=/home/ci-runner/.gradle/wrapper/dists/gradle-7.6.1-all/942lu1p9i6mhoyzmt401s4g74/gradle-7.6.1/lib, -Dgradle.user.home=/home/ci-runner/.gradle, -Dgradle.worker.jar=/home/ci-runner/.gradle/caches/7.6.1/workerMain/gradle-worker.jar, -Dio.netty.noKeySetOptimization=true, -Dio.netty.noUnsafe=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Djava.awt.headless=true, -Djava.library.path=/home/ci-runner/k-NN/jni/release, -Djava.locale.providers=SPI,COMPAT, -Djdk.attach.allowAttachSelf=true, -Djna.nosys=true, -Dopensearch.scripting.update.ctx_in_params=false, -Dopensearch.search.rewrite_sort=true, -Dopensearch.transport.cname_in_publish_address=true, -Dorg.gradle.internal.worker.tmpdir=/home/ci-runner/k-NN/build/tmp/test/work, -Dorg.gradle.native=false, -Dtests.artifact=opensearch-knn, -Dtests.gradle=true, -Dtests.logger.level=WARN, -Dtests.security.manager=false, -Dtests.seed=1D74642C8A5A3ABE, -Dtests.task=:test, -XX:+HeapDumpOnOutOfMemoryError, -esa, --illegal-access=warn, -javaagent:../../tmp/expandedArchives/org.jacoco.agent-0.8.7.jar_3a83c50b4a016f281c4e9f3500d16b55/jacocoagent.jar=destfile=../../jacoco/test.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false, -XX:HeapDumpPath=/home/ci-runner/k-NN/build/heapdump, -Xms512m, -Xmx512m, -Dfile.encoding=US-ASCII, -Djava.io.tmpdir=/home/ci-runner/k-NN/build/testrun/test/temp, -Duser.country=US, -Duser.language=en, -Duser.variant, -ea]
  1> [2024-02-07T14:31:38,738][WARN ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] version [2.11.1-SNAPSHOT] is a pre-release version of OpenSearch and is not suitable for production
  1> [2024-02-07T14:31:38,738][INFO ][o.o.p.PluginsService     ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] no modules loaded
  1> [2024-02-07T14:31:38,739][INFO ][o.o.p.PluginsService     ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] loaded plugin [org.opensearch.knn.plugin.KNNPlugin]
  1> [2024-02-07T14:31:38,739][INFO ][o.o.p.PluginsService     ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] loaded plugin [org.opensearch.test.MockHttpTransport$TestPlugin]
  1> [2024-02-07T14:31:38,739][INFO ][o.o.p.PluginsService     ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] loaded plugin [org.opensearch.transport.nio.MockNioTransportPlugin]
  1> [2024-02-07T14:31:38,739][INFO ][o.o.e.ExtensionsManager  ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] ExtensionsManager initialized
  1> [2024-02-07T14:31:38,741][INFO ][o.o.e.NodeEnvironment    ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] using [1] data paths, mounts [[/ (overlay)]], net usable_space [475.7gb], net total_space [484.4gb], types [overlay]
  1> [2024-02-07T14:31:38,741][INFO ][o.o.e.NodeEnvironment    ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] heap size [512mb], compressed ordinary object pointers [true]
  1> [2024-02-07T14:31:38,743][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] node name [mock_ node], node ID [NoDIkP__T_-xKXOs_____w], cluster name [single-node-cluster-TEST_WORKER_VM=[4]-CLUSTER_SEED=[-7675565384823056753]-HASH=[1185C65F8D7]], roles [ingest, remote_cluster_client, data, cluster_manager]
  1> [2024-02-07T14:31:38,765][DEPRECATION][o.o.d.c.s.Settings       ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] [index.store.hybrid.mmap.extensions] setting was deprecated in OpenSearch and will be removed in a future release! See the breaking changes documentation for the next major version.
  1> [2024-02-07T14:31:38,785][INFO ][o.o.d.DiscoveryModule    ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] using discovery type [zen] and seed hosts providers [settings]
  1> [2024-02-07T14:31:38,821][WARN ][o.o.g.DanglingIndicesState] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] gateway.auto_import_dangling_indices is disabled, dangling indices will not be automatically detected or imported and must be managed manually
  1> [2024-02-07T14:31:38,836][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] initialized
  1> [2024-02-07T14:31:38,837][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] starting ...
  1> [2024-02-07T14:31:38,847][INFO ][o.o.t.TransportService   ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] publish_address {127.0.0.1:9300}, bound_addresses {127.0.0.1:9300}
  1> [2024-02-07T14:31:38,848][INFO ][o.o.t.TransportService   ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] Remote clusters initialized successfully.
  1> [2024-02-07T14:31:38,868][INFO ][o.o.c.c.ClusterBootstrapService] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] no discovery configuration found, will perform best-effort cluster bootstrapping after [3s] unless existing cluster-manager is discovered
  1> [2024-02-07T14:31:41,869][INFO ][o.o.c.c.Coordinator      ] [mock_ node] setting initial configuration to VotingConfiguration{NoDIkP__T_-xKXOs_____w}
  1> [2024-02-07T14:31:41,984][INFO ][o.o.c.s.MasterService    ] [mock_ node] elected-as-cluster-manager ([1] nodes joined)[{mock_ node}{NoDIkP__T_-xKXOs_____w}{F1vrdlQVRXyX30G9Yv94VQ}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true} elect leader, _BECOME_CLUSTER_MANAGER_TASK_, _FINISH_ELECTION_], term: 1, version: 1, delta: cluster-manager node changed {previous [], current [{mock_ node}{NoDIkP__T_-xKXOs_____w}{F1vrdlQVRXyX30G9Yv94VQ}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]}
  1> [2024-02-07T14:31:41,994][INFO ][o.o.c.c.CoordinationState] [mock_ node] cluster UUID set to [3qM8CiSXRQ25JXFJg4_uCw]
  1> [2024-02-07T14:31:42,004][INFO ][o.o.c.s.ClusterApplierService] [mock_ node] cluster-manager node changed {previous [], current [{mock_ node}{NoDIkP__T_-xKXOs_____w}{F1vrdlQVRXyX30G9Yv94VQ}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]}, term: 1, version: 1, reason: Publication{term=1, version=1}
  1> [2024-02-07T14:31:42,005][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] started
  1> [2024-02-07T14:31:42,005][INFO ][o.o.d.PeerFinder         ] [mock_ node] setting findPeersInterval to [1s] as node commission status = [true] for local node [{mock_ node}{NoDIkP__T_-xKXOs_____w}{F1vrdlQVRXyX30G9Yv94VQ}{127.0.0.1}{127.0.0.1:9300}{dimr}{shard_indexing_pressure_enabled=true}]
  1> [2024-02-07T14:31:42,010][INFO ][o.o.g.GatewayService     ] [mock_ node] recovered [0] indices into cluster_state
  1> [2024-02-07T14:31:42,013][INFO ][o.o.p.PluginsService     ] [mock_ node] PluginService:onIndexModule index:[myindex/nzUpSzPzTlSYdkKWI4iZnQ]
  1> [2024-02-07T14:31:42,015][INFO ][o.o.c.m.MetadataCreateIndexService] [mock_ node] [myindex] creating index, cause [api], templates [], shards [1]/[1]
  1> [2024-02-07T14:31:42,029][INFO ][o.o.p.PluginsService     ] [mock_ node] PluginService:onIndexModule index:[myindex/nzUpSzPzTlSYdkKWI4iZnQ]
  1> [2024-02-07T14:31:42,077][INFO ][o.o.p.PluginsService     ] [mock_ node] PluginService:onIndexModule index:[myindex/nzUpSzPzTlSYdkKWI4iZnQ]
  1> [2024-02-07T14:31:42,097][INFO ][o.o.p.PluginsService     ] [mock_ node] PluginService:onIndexModule index:[myindex/nzUpSzPzTlSYdkKWI4iZnQ]
  1> [2024-02-07T14:31:42,113][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] stopping ...
  1> [2024-02-07T14:31:42,117][INFO ][o.o.n.Node               ] [testFilteredSearchAdvanceSetting_whenValuesProvidedByUsers_thenValidateSameValues] stopped
```

**Comment by heemin32** [comment] 2024-02-07 21:26
Instead of removing the validation, shouldn't we just comment it out temporary and create a new issue to dig in why it is failing? I guess somehow it gets over written by other threads?

**Comment by jmazanec15** [comment] 2024-02-07 23:44
@heemin32 Do we need the validation? Removal was because we dont really need the check in our tests and it could take awhile to debug. So having it does not seem to add value

**Comment by heemin32** [comment] 2024-02-08 00:00
Okay. The warning is coming from opensearch core because if are trying to update deprecated setting?
At least we need to leave a comment on why we set enableWarningCheck as false then.

**Comment by junqiu-lei** [comment] 2024-02-08 00:25
@heemin32 Added comment on enableWarningCheck method https://github.com/opensearch-project/k-NN/pull/1442/commits/94aaa9024da5c7996481a2a51a38b2681d650aac

**Comment by junqiu-lei** [comment] 2024-02-09 02:24
Closing this issue since https://github.com/opensearch-project/k-NN/pull/1442 got merged

**Closed by junqiu-lei** 2024-02-09 02:24 UTC
Labels: bug
