### ISSUE TITLE
[BUG] code_size values > 4 are not accepted

### ISSUE THREAD

**Issue by richjames0** [opensearch-project/k-NN#594] opened 2022-10-26 01:57 UTC
We seem to be running into problems with code_size values above 4, in that this is triggering the OOM or incorrectly specified index error message. It could be OOM but seems more likely it doesn’t like that this falls under the index specification option of the aggregated error message. https://opensearch.org/docs/latest/search-plugins/knn/knn-index#method-definitions says that the max value for the code_size is 8, however it does not work (and in any case, we believe higher values should also be allowed, e.g. up to the size of the raw encoding).

To reiterate there are potentially two issues here:
1. Docs claim code size of 8 should be allowed but it isn't
2. Code size > 8 should actually be allowed (but isn't, per docs and experience)

**Repro in raw Faiss**
```
import numpy as np
import faiss
import os
import math
np.random.seed(0)
num_points,dimension = 400,16
vector_data = np.random.random((num_points, dimension))
db_vectors = vector_data.astype('float32').copy(order="C")
code_size = 8
nlist = math.floor(math.sqrt(num_points))
quantizer = faiss.IndexFlatL2(dimension)
index_ivfpq = faiss.IndexIVFPQ(quantizer, dimension, 4, code_size, 8)
print(index_ivfpq.nlist)
index_ivfpq.train(db_vectors)  # train on the database vectors
Index_ivfpq.is_trained
True
```

**Repro in OpenSearch**
1. Create index
```
PUT /issue2-index
{
  "settings" : {
    "number_of_shards" : 3,
    "number_of_replicas" : 1
  },
  "mappings": {
       "properties": {
       "train-field": {
           "type": "knn_vector",
           "dimension": 16
      }
   }
  }
}
```
3. Add data to that index
```
node_modules/elasticdump/bin/elasticdump --input=/data/home/marialomeli/data/git_issue2.jsonl --output=https://10.100.79.75/issue2-index --type=data --overwrite
```
[We can verify the data was added with a GET request]

4. Train index
```
POST /_plugins/_knn/models/my-model-issue2/_train
{
  "training_index": "issue2-index",
  "training_field": "train-field",
  "dimension": 16,
  "method": {
    "name": "ivf",
    "engine": "faiss",
    "parameters": {
      "nlist": 4,
      "encoder": {
        "name": "pq",
        "parameters": {
          "code_size": 8,
          "m": 8
        }
      }
    }
  }
}
```
Result: Error from OpenSearch
```
GET /_plugins/_knn/models/my-model-issue2
{
  "model_id" : "my-model-issue2",
  "model_blob" : "",
  "state" : "failed",
  "timestamp" : "2022-10-25T17:50:54.115284Z",
  "description" : "",
  "error" : "Failed to execute training. May be caused by an invalid method definition or not enough memory to perform training.",
  "space_type" : "l2",
  "dimension" : 16,
  "engine" : "faiss"
}
```

**Comment by jmazanec15** [comment] 2022-10-26 17:28
@richjames0  Looking into this

**Comment by richjames0** [comment] 2022-10-27 20:36
Thanks! This would make a huge difference for us, as it would unlock non-toy uses of indexing

**Comment by jmazanec15** [comment] 2022-11-07 18:57
Hi @richjames0 

I wrote some repro code here running locally and I am not able to reproduce the issue when code_size = 4 or 8 and also tried nlist of 4 or 20. (https://gist.github.com/jmazanec15/403b5943347861b04c70cc7383f1a9a7).

In the above code, I do get a similar error when training data is too low. I am wondering if training data is getting indexed properly. Could you check the following api's?
1. /_cat/indices
2. /issue2-index/_mapping?pretty

Also, do you run the train api instantaneously after ingesting the training data?

**Comment by richjames0** [comment] 2022-11-09 22:38
Thanks Jack. I'll give this a go - this update slipped past me (need to fix my rules!)

I assume code_size > 8 wouldn't work (e.g. 96 is a common one we use)

**Comment by tommasomac** [comment] 2023-03-10 09:25
Hi @richjames0 , @jmazanec15 , 
were you able to solve this?

I get the same error while training a FAISS index on OpenSearch (following the first 4 code snippets on this tutorial https://opensearch.org/docs/1.3/search-plugins/knn/approximate-knn/#building-a-k-nn-index-from-a-model).

Thanks

**Comment by jmazanec15** [comment] 2023-03-22 22:02
Hi @tommasomac is there enough training data? Were there any log messages? For the above, the root cause was a mix up in code_size and M variables. M in OpenSearch refers to how many sub vectors to break up the vector into and code_size refers to how many bits to encode each subvector. I believe the meaning is flipped in faiss.

**Comment by jmazanec15** [comment] 2023-04-12 22:43
Closing. Please open new issue if there is any follow up.

**Closed by jmazanec15** 2023-04-12 22:43 UTC
Labels: bug
