### ISSUE TITLE
[BUG] After compilation, the file libopensearchknn_nmslib.so could not be found

### ISSUE THREAD

**Issue by xiaodizi** [opensearch-project/k-NN#1326] opened 2023-11-28 06:42 UTC
I pulled the main branch and compiled it locally. But after compiling successfully, can not find the lib folder, and the folder of libopensearchknn_nmslib.so and other several files.

The jnilib file can be compiled from the release folder in the jni folder. Is this normal?

But after I installed the compiled opensearch-knn-3.0.0.0-SNAPSHOT.zip package, knn was not working. Because there is no lib folder or related files.

<img width="1698" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/3ce4b84d-391d-42bd-a9fa-4152cd7c95ce">

<img width="425" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/d6a5f1ce-1490-4cf2-ad88-4704abc313f0">
<img width="560" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/2ca867d6-e60e-4835-a23e-a92d0a77d027">

**Comment by heemin32** [comment] 2023-11-28 17:55
Did you follow DEVELOPER_GUIDE.md? https://github.com/opensearch-project/k-NN/blob/main/DEVELOPER_GUIDE.md

**Comment by xiaodizi** [comment] 2023-11-29 00:57
> Did you follow DEVELOPER_GUIDE.md? https://github.com/opensearch-project/k-NN/blob/main/DEVELOPER_GUIDE.md

Yes, I built it on a mac.
The execution is

`./gradlew build`

cmake is installed

I'm using brew install to install cmake. Does this matter?


<img width="378" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/bbab3986-13aa-4f0f-b783-fdde3cf8062e">
<img width="375" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/0d340130-a301-48d7-9a7f-d399f5c95a84">
<img width="398" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/88015322-b9df-4909-bf66-614df7fab4e4">

**Comment by xiaodizi** [comment] 2023-11-29 00:58
I'm sorry, I accidentally shut it down. Open it up again

**Comment by xiaodizi** [comment] 2023-11-29 01:00
Sorry, I accidentally closed the question. But do I know how to open it

**Comment by heemin32** [comment] 2023-11-29 04:34
@ryanbogan Could you help here?

**Comment by xiaodizi** [comment] 2023-11-30 07:36
<img width="800" alt="image" src="https://github.com/opensearch-project/k-NN/assets/10411525/e4ea8540-37db-43ff-9a8d-4ebaccd91e48">

Problem solved, looking for a long time code, found here to limit the compilation results of different operating systems. So, that's it...

**Comment by ryanbogan** [comment] 2024-01-08 18:59
Is this something that we need to add to the codebase in a PR?

**Comment by heemin32** [comment] 2024-01-08 22:44
> Is this something that we need to add to the codebase in a PR?

It seems the issue is resolved. Closing it.

**Closed by heemin32** 2024-01-08 22:44 UTC
Labels: bug, untriaged
