### ISSUE TITLE
[BUG] KNN doesn't release memory when close index

### ISSUE THREAD

**Issue by ylwu-amzn** [opensearch-project/k-NN#1012] opened 2023-07-28 05:15 UTC
Run big KNN indexes, and see memory usage keep high as 95%. Close one big KNN index, but memory usage still keep high.
Have to delete the KNN index to release the memory. After deleting the index, can see memory usage goes down to 75%.

Seems like a bug that when close an index, KNN doesn't release the memory.

**Comment by jmazanec15** [comment] 2023-08-01 21:44
@ylwu-amzn Thanks for reporting this. Yes, the problem is that we do watch for the files to be deleted to free memory as opposed to freeing memory when the IndexReader gets closed.

I think a fix for this is to implement a DocValuesReader that frees memory when it is closed.

**Comment by jmazanec15** [comment] 2024-10-16 00:41
Addressed in 2.18 with #2182

**Comment by luyuncheng** [comment] 2024-10-17 09:15
@jmazanec15 After  #1946, when close the indices, it would release the memory.

**Closed** 2024-10-31 17:39 UTC
Labels: bug
