### ISSUE TITLE
Synonyms with ANN

### ISSUE THREAD

**Issue by aishwaryabajaj-54** [opensearch-project/k-NN#794] opened 2022-12-23 06:32 UTC
Synonyms do not work with ANN OpenSearch.
Let’s say I have added a synonym like-
universe => cosmos
Now, I want to search the keyword “universe” and I have created embeddings for the search term “universe” and used it in my search query with ANN to get results for the keyword “universe” which is working fine. But with synonyms, If I search for the term “universe” I should be able to get results for “cosmos” as well and that is not working. How can we make it to work?

**Comment by navneet1v** [comment] 2023-03-09 01:34
Removing bug tag as this is not a bug.

**Comment by aishwaryabajaj-54** [comment] 2023-03-09 12:05
> You can support OR operator in keyword search with "should". Please check if this query can work for you.
The above query would mean synonyms would work with the BM25 algorithm but it should work with KNN. 

I explored msearch but in our use case, we have the capability to add dynamic and multiple synonyms for a keyword. If we have a search term like: “approximate nearest neighbor” and all three keywords have synonyms so there will be 9 queries with the combinations of keywords and their synonyms + 1 original search term. So, running multiple queries in a single request or using msearch would become unscalable. 

It would be helpful if we can discuss and explore ways to support synonyms with KNN.

**Comment by navneet1v** [comment] 2023-03-09 22:09
> I explored msearch but in our use case, we have the capability to add dynamic and multiple synonyms for a keyword. If we have a search term like: “approximate nearest neighbor” and all three keywords have synonyms so there will be 9 queries with the combinations of keywords and their synonyms + 1 original search term. So, running multiple queries in a single request or using msearch would become unscalable.

@aishwaryabajaj-54 right now for your request the only options I can see is either using _msearch or using should clause to wrap both keyword search and K-NN Search.

Possible Limitation:
1. The size of the whole query can keep on increasing the moment we have more synonyms.
2. The sub-queries will be executed in sequence, hence there can be performance concern. For limited number of queries may be you can see how you can use _msearch in this case, but again it will lead to perf degradation as you have seen earlier.


Next Steps:
1. I will go ahead and create a github issue for this feature request and attach this issue over there.
2. Currently, the k-nn engines we have might not support this array of Vectors as query. I remember that Fassis may support it natively. But more digging needs to be done and come up with a possible solution.
3. I am going to put the feature in our backlog, feel free to contribute. 
 
> It would be helpful if we can discuss and explore ways to support synonyms with KNN.

I will be happy to discuss the approaches to come up with a solution for your ask.

**Comment by navneet1v** [comment] 2023-03-09 23:45
@aishwaryabajaj-54 created this feature request: https://github.com/opensearch-project/k-NN/issues/796

We can do solution level discussion on that issue. Feel free to propose any other solution which you have in mind.

**Comment by aishwaryabajaj-54** [comment] 2023-03-23 10:24
@navneet1v, Thank you for the solutions and for creating a feature request.

**Comment by navneet1v** [comment] 2023-03-23 18:19
Closing this issue. The further discussion about what should be the best approach will be discussed here: https://github.com/opensearch-project/k-NN/issues/796 

Feel free to add a +1 or if possible add a comment with your usecase, for helping in prioritization of the issue.

**Closed by navneet1v** 2023-03-23 18:19 UTC
Labels: Features, enhancement
